apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nginx-claim1
  name: nginx-claim1
spec:
  storageClassName: ""
  volumeName: nginx-pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
